using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace survey.Model
{
    public class CouponCode
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public int code { get; set; }
        public ObjectId userId { get; set; }
        public string dateGenerated { get; set; }
        public string dateRedeemed { get; set; }
    }
}
